### ISSUE TITLE
Add any basic Java Program and star this repo

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/Java-Programs#1]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**Comment by SomilAjmera** [comment]
Hello @Pavan-Kamthane 
Can you please assign this issue to me? I have a good knowledge in Java language. Thank you.

**Comment by Wolverine-08** [comment]
@Pavan-Kamthane assign this to me also I have good grasp of java language

**Comment by Pavan-Kamthane** [comment]
@Wolverine-08 You can PR directly

**Comment by ShaluMishra13** [comment]
hey please assing this to me . I can do it well.

**Comment by Pavan-Kamthane** [comment]
@ADITYADAS1999 @ShaluMishra13 pr directly

**Comment by Harsh0326** [comment]
Hey @ADITYADAS1999 can you assign me?

**Comment by ADITYADAS1999** [comment]
> Hey @ADITYADAS1999 can you assign me?

sry i'm not the project admin ask [Pavan-Kamthane](https://github.com/Pavan-Kamthane) 💁🏻‍♂️ for assigning
