### ISSUE TITLE
Upload a simple Java program in your named folder.

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/Java-Programs#129]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**You can create a PR directly, no need to assign anyone**

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by 20RitikSingh** [comment]
I have sent a pull request with "hacktober pr"

**Comment by Nilesh-Ghone** [comment]
I will try this. Thanks.

**Comment by Nilesh-Ghone** [comment]
PR #187 created. Please kindly merge to main branch. Thank you!

**Comment by Nilesh-Ghone** [comment]
Hi @Pavan-Kamthane,

I have added 'Prototype Design Pattern' information and codebase. - PR #192. Please kindly merge into main branch.

Thank you.
