### ISSUE TITLE
File --> file(folder)

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/Java-Programs#37]
Like some one added a simple **hello world** program 

What you have to do is :-
Create same named folder  
**Hello World**
And add that file in it.

Hope you understand Issue.

Thank you 😊.

**Comment by Abhinav092003** [comment]
please assign me this issue if posiible @Pavan-Kamthane

**Comment by rkt1234** [comment]
please assign me this issue if posiible @Pavan-Kamthane

**Comment by Pavan-Kamthane** [comment]
@rkt1234 assigned
