### ISSUE TITLE
Add Java Projects 


### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/Java-Programs#4]
You can add any basic project of Java .

**Comment by Sengar123** [comment]
hello,sir kindly assign this to me. I want to contribute

**Comment by suresh37** [comment]
@Pavan-Kamthane Added some String programs. Please check and merge my PR

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me.

**Comment by Madhavv024** [comment]
Hello sir, I want to add some good arrays dynamic programming solutions, kindly assign this to me

**Comment by suresh37** [comment]
@Pavan-Kamthane Please check and merge my PR (longest substring using sliding window using java)

**Comment by Kushagrafeb29** [comment]
Hi can you assign this to me.I am really interested in it

**Comment by Kushagrafeb29** [comment]
How do I pull a request in Github ?
I have great knowledge of Java and can add some great projects.

**Comment by Pavan-Kamthane** [comment]
Yes

**Comment by Pavan-Kamthane** [comment]
Please check contribution.md file in my repo 
Or you can refer some YouTube videos also.

**Comment by devjain2309** [comment]
assign me this task
