### ISSUE TITLE
File ---> file named folder 

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/Java-Programs#65]
Hey guys I have one task for you.

In this repository those files which are not in folder_**(except readme.md and contribution.md)**_ , put them in folder of same filed name.
**And if they are already in folder then don't touch them.**

Example if someone added **helloworld**_program then you have to create a helloworld named folder then add this **helloworld** file, that set.

I think it is enough to explain.

Thanks.

**Comment by Frey0-0** [comment]
I would like to work on this @Pavan-Kamthane

**Comment by Rohit-R2000** [comment]
can i work on this

**Comment by prerit2001** [comment]
Assign me this.

**Comment by vinay4563** [comment]
Please assign me this issue, I will do the required changes

**Comment by Yaswanthb13** [comment]
Can you assign me with this issue, i will work on this

**Comment by Harsh0326** [comment]
Hey @prerit2001 can you assign me
