### ISSUE TITLE
Add contributor profile image in readme.md 

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/Java-Programs#7]
All you have to add contributor profile image in readme.md file 

**Thank You**

**Comment by Wolverine-08** [comment]
@Pavan-Kamthane assign to me

**Comment by Pavan-Kamthane** [comment]
@Wolverine-08 
Done

**Comment by aashish-1904** [comment]
Hello, assign this issue to me

**Comment by Pavan-Kamthane** [comment]
@aashish-1904 start ur work
